### ISSUE TITLE
Possibility to generate fake visits with a specific Channel Type

### ISSUE THREAD

**Issue by jorgeuos** [piwik/plugin-VisitorGenerator#130]
Like the title said.

Is it possible to generate some visits with a specific Channel Type?
In my case I want some more fake visits with Campaigns as Channel Type to properly troubleshoot an issue I'm working on.

Br, Jorge

**Comment by snake14** [comment]
Hi @jorgeuos . Thank you for taking the time to create an issue. Looking at the code that generates fake visits, it appears to append campaign parameters, like `pk_campaign`, to the URL every few requests. Could you please provide more detail about what you're experiencing and what you would like to see? Is it not tracking those requests as having campaigns, because that could possibly be bug?

**Comment by snake14** [comment]
Hi @jorgeuos . It's been a while since you submitted this issue and you haven't responded to my request for more information. I'm going to close this issue for now, but please let us know if you feel that it should be reopened.
