### ISSUE TITLE
For WordPress Version ?

### ISSUE THREAD

**Issue by d4op** [piwik/plugin-VisitorGenerator#67]
possible to use this plugin for the matomo Wordpress version ?

**Comment by tsteur** [comment]
Hi @d4op I just tested it and unfortunately not working so far. To make this work we'd need to:

* Add a plugin file `VisitorGenerator.php`
* When it is used in WordPress not add it as development menu item but as a different menu item since the development wouldn't be enabled in WordPress and therefore not shown
* We'd need to check that it actually does work. I tried to use it and it says it generated like 250 visits within 1 second which is not possible so there must be something not quite right.
